VolnaYuga/urls.py
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from accounts.views import login_request, logout_request, password_reset_request
from core.sitemaps import HotelSitemap, RegionSitemap
from core.views import AboutPage, ContactPage, RentPage, HomePage
from django.conf import settings
from django.conf.urls.static import static

from hotel.models import Hotel
from region.views import RegionAutocomplete, HotelSearchBlock
from django.conf.urls import handler404

sitemaps = {
    'hotel': HotelSitemap,
    'region': RegionSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'city-autocomplete/',
        RegionAutocomplete.as_view(),
        name='city-autocomplete',
    ),
    path('search/', HotelSearchBlock.as_view(), name='hotel_search_block'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    path('about/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('rent/', RentPage.as_view(), name='rent'),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('page/', include('page.urls', namespace='page')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('user_queries/', include('userQueries.urls', namespace='userQueries')),
    # path('register/', register_request, name="register"),
    path('login/', login_request, name="login_s"),
    path('logout/', logout_request, name="logout_s"),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('<region_slug>/attraction/', include('attraction.urls', namespace='attraction')),
    path('review/', include('review.urls', namespace='review')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('<slug>/', include('region.urls', namespace='region')),
    path('', HomePage.as_view(), name='home'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from hotel.models import BookmarkHotel
from hotel.views import BookmarkView, favorites_list, add_to_favorites, remove_from_favorites

app_name = 'hotel'

urlpatterns = [
    path('<id>/bookmark/', add_to_favorites, name='hotel_bookmark'),
    path('bookmarks/', favorites_list, name='bookmarks'),
]

page/urls.py
from django.urls import path
from .views import PageDetail


app_name = 'page'

urlpatterns = [
    path('<slug:slug>/', PageDetail.as_view(), name='page_detail'),
]

region/urls.py
from django.urls import path
from region.views import HotelDetail, HotelFilterByType, hotel_list, HotelFilterByService, HotelFilterByTypeAndService, \
    HotelSearchBlock
from region.views import RegionDetail


app_name = 'region'

urlpatterns = [
    path('', RegionDetail.as_view(), name='region_detail'),
    path('filter/', hotel_list, name='hotel_filter_left'),
    path('search/', HotelSearchBlock.as_view(), name='hotel_search_block'),
    path('<int:pk>/', HotelDetail.as_view(), name='hotel_detail'),
    path('<slug:type_slug>/', HotelFilterByType.as_view(), name='hotel_type_filter'),
    path('service/<slug:service_slug>/', HotelFilterByService.as_view(), name='hotel_service_filter'),
    path('<slug:type_slug>/<slug:service_slug>/', HotelFilterByTypeAndService.as_view(),
         name='hotel_type_service_filter'),

]

hotel/models.py
import datetime
from datetime import date
from django.db import models
from django.db.models import Avg, Sum, Min
from accounts.models import MyUser
from ckeditor.fields import RichTextField
from region.models import Region


class TypeofObject(models.Model):
    """Типы объектов сдачи"""
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')
    image = models.ImageField(upload_to='hotel/hoteltype', null=True, blank=True, verbose_name='Изображение')
    services = models.ManyToManyField('ServiceFilterofObject', blank=True,
                                      verbose_name='Какие критерии жилья отображать на странице')

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = ' Типы объектов размещения'

    def __str__(self):
        return self.title


class ServiceFilterofObject(models.Model):
    """Фильтр критериев удобств объектов сдачи"""
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')
    image = models.ImageField(upload_to='hotel/filterservice', null=True, blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'Критерий удобства'
        verbose_name_plural = ' Критерии удобства'

    def __str__(self):
        return self.title


OPTIONCATEGORYCHOICE = (
    ('food', ('Питание')),
    ('service', ('Удобства и услуги')),
    ('booking', ('Условия бронирования')),
)


class HotelOption(models.Model):
    """Опции объекта"""
    title = models.CharField(max_length=100, verbose_name='Название')
    comment = models.CharField(max_length=100, blank=True, verbose_name='Комментарии')
    category = models.CharField(max_length=50, choices=OPTIONCATEGORYCHOICE, default='food', verbose_name='Категория')
    icon = models.CharField(max_length=50, blank=True, verbose_name='Класс иконки font-awesome')

    class Meta:
        verbose_name = 'Опцию'
        verbose_name_plural = ' Опции для гостиниц'

    def __str__(self):
        return self.title


class Distance(models.Model):
    """Расстояния от гостиницы"""
    title = models.CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Расстояние до обьекта'
        verbose_name_plural = 'Расстояния до объектов'

    def __str__(self):
        return self.title


WALKMETHODCHOICE = (
    ('walk', ('Пешком')),
    ('avto', ('На авто')),
)


class DistanceTime(models.Model):
    """Расстояние до объектов"""
    distance = models.ForeignKey(Distance, on_delete=models.CASCADE, verbose_name='Объект расстояния')
    time = models.IntegerField(verbose_name='Время в минутах', blank=True, null=True)
    method = models.CharField(max_length=10, choices=WALKMETHODCHOICE, blank=True, null=True, verbose_name='Метод')
    hotel = models.ForeignKey('Hotel', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Гостиница')

    class Meta:
        verbose_name = 'Время до объекта'
        verbose_name_plural = 'Время до объектов'

    def __str__(self):
        return self.distance.title


BEACHCHOICE = (
    ('galka', ('Галька')),
    ('pesok', ('Песок')),
)

BEACHREMOTENESS = [
    ('100', '100'),
    ('200', '200'),
    ('500', '500'),
    ('800', '800'),
    ('1000', '1000'),
    ('1500', '1500'),
]


class HotelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True)


class Hotel(models.Model):
    """Отель"""
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='Владелец')
    pub_date = models.DateField(default=datetime.date.today, verbose_name='Дата публикации')
    title = models.CharField(max_length=100, verbose_name='Название')
    meta_title = models.CharField(max_length=100, blank=True, verbose_name='Мета заголовок')
    meta_description = models.TextField(blank=True, verbose_name='Мета описание')
    premium = models.BooleanField(default=False, verbose_name='Премиум гостиница')
    object_type = models.ManyToManyField(TypeofObject, blank=True, verbose_name='Тип жилья')
    object_service = models.ManyToManyField(ServiceFilterofObject, blank=True, verbose_name='Фильтр по критериям жилья')
    address = models.CharField(max_length=100, verbose_name='Адрес (без указания города)')
    city = models.ForeignKey(Region, on_delete=models.CASCADE, limit_choices_to={'is_city': True},
                             related_name='hotels', verbose_name='Город')
    remoteness = models.CharField(max_length=10, blank=True, choices=BEACHREMOTENESS, default=1,
                                  verbose_name='Расстояние до моря')
    beach = models.CharField(max_length=50, blank=True, choices=BEACHCHOICE, default='1000', verbose_name='Пляж')
    centr = models.CharField(max_length=20, blank=True, verbose_name='Расстояние до центра')
    options = models.ManyToManyField(HotelOption, blank=True, verbose_name='Опции')
    description = RichTextField(blank=True, verbose_name='Описание')
    video = models.URLField(blank=True, verbose_name='Ссылка на видео объекта')
    distance = models.ManyToManyField(Distance, through='DistanceTime', verbose_name='Объекты рядом')
    prepayment = models.CharField(max_length=10, blank=True,
                                  verbose_name='Размер предоплаты в % или в сутках проживания')
    free_cancel = models.CharField(max_length=100, blank=True, verbose_name='Условия бесплатной отмены брони')
    early_booking_discount = models.IntegerField(null=True, blank=True, verbose_name='Скидка на раннее бронирование')
    requisites = models.TextField(blank=True, verbose_name='Реквизиты')
    prepayments_term = models.BooleanField(default=0, verbose_name='Без предоплаты')
    minimum = models.IntegerField(blank=True, null=True, verbose_name='Минимальный срок проживания в сутках')
    chek_in = models.TimeField(blank=True, null=True, verbose_name='Время заселения')
    chek_out = models.TimeField(blank=True, null=True, verbose_name='Время выезда')
    pets = models.BooleanField(default=0, verbose_name='Размещение животных')
    child = models.BooleanField(default=0, verbose_name='Размещение детей')
    another_rules = models.TextField(blank=True, verbose_name='Другие правила')
    published = models.BooleanField(default=0, verbose_name='Опубликовать гостиницу')
    objects = models.Manager()
    filter_objects = HotelManager()

    class Meta:
        verbose_name = ' Обьект размещения'
        verbose_name_plural = ' Гостиницы'

    def __str__(self):
        return self.title

    def get_min_price(self):
        return self.numbers.all().aggregate(min_price=Min('prices__price'))['min_price']



class BookmarkHotel(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name="Пользователь")
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, verbose_name='Объект')

    def __str__(self):
        return self.user.email


class HotelPhoto(models.Model):
    """Фотографии на странице фильтрации"""
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='hotel/hotel_photo_thumb', null=True, default='profile_image/none/no-img.png',
                              verbose_name='Изображение')

    class Meta:
        verbose_name = 'Фотографию'
        verbose_name_plural = 'Фотографии объекта для страниц фильтрации'
        ordering = ['id']

    def __str__(self):
        return self.image.name


class HotelContact(models.Model):
    """Контакты объекта"""
    hotel = models.ForeignKey(Hotel, default=1, on_delete=models.CASCADE, verbose_name='Гостиница')
    phone = models.CharField(max_length=12, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Email')
    photo = models.FileField(upload_to='hotel/contacts', null=True, blank=True, verbose_name='Фотография')
    name = models.CharField(max_length=100, verbose_name='ФИО')
    skype = models.BooleanField(default=0)
    whatsapp = models.BooleanField(default=0)
    telegram = models.BooleanField(default=0)
    viber = models.BooleanField(default=0)

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты объектов размещения'

    def __str__(self):
        return self.name


class NumberOption(models.Model):
    """Опции объекта"""
    title = models.CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Опцию'
        verbose_name_plural = ' Опции для номеров'

    def __str__(self):
        return self.title


class Number(models.Model):
    ORDERCHOICE = (
        ('number', ('за номер')),
        ('people', ('за человека')),
    )

    order_choice = models.CharField(max_length=10, choices=ORDERCHOICE, default='за номер',
                                    verbose_name='Цена в объявлении')
    hotel = models.ForeignKey(Hotel, default=1, on_delete=models.CASCADE, related_name='numbers', verbose_name='Отель')
    title = models.CharField(max_length=100, verbose_name='Название')
    room_number = models.IntegerField(null=True, blank=True, verbose_name='Количество комнат')
    sleep_place = models.IntegerField(null=True, blank=True, verbose_name='Количество спальных мест')
    room_square = models.IntegerField(null=True, blank=True, verbose_name='Площадь комнаты')
    additional_palces = models.IntegerField(null=True, blank=True, verbose_name='Дополнительные места')
    furniture = RichTextField(blank=True, verbose_name='Мебель')
    options = models.ManyToManyField(NumberOption, blank=True, verbose_name='Опции')

    class Meta:
        verbose_name = ' Номер'
        verbose_name_plural = ' Номера'

    def __str__(self):
        return self.hotel.title + ' - ' + self.title

    def get_min_price(self):
        """Самая низкая цена номера"""
        return Price.objects.filter(number=self).aggregate(min_price=Min('price'))['min_price']

    def get_price_today(self):
        """Цена номера на сегодня"""

review/models.py
from datetime import datetime
from django.db import models

from hotel.models import Hotel


class Review(models.Model):
    """Отзыв с оценкой"""
    name = models.CharField(max_length=300, verbose_name='Имя')
    city = models.CharField(max_length=200, blank=True, verbose_name='Город')
    born = models.DateField(default=datetime.now, verbose_name='Дата создания')
    period = models.CharField(max_length=50, verbose_name='Период отдыха')
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, verbose_name='Отель')
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    rating = models.IntegerField(choices=RATING_CHOICES, default='5', verbose_name='Рейтинг')
    body = models.TextField(verbose_name='Описание')
    email = models.EmailField()
    verificated = models.BooleanField(default=False, verbose_name='Активен')

    class Meta:
        verbose_name_plural = '    Отзывы'
        verbose_name = 'Отзыв'

    def __str__(self):
        return "%s: %s" % (self.name, self.hotel)

templates/hotel/admin_thumbnail.html
{% load thumbnail %}
<a href="{{ photo.url }}">
    {% thumbnail photo "150x120" crop='center' as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
</a>

templates/hotel/bookmarks.html
{% extends 'base.html' %}
{% load static thumbnail %}
{% block meta %}
    <title>{{ object.title }}</title>
{% endblock %}
{% block header %}
    <header class="main-header about-header">
        <div class="container">
            {% include 'include/main-menu.html' %}
            <div class="headerTitle">
                <h1>Избранное</h1>
            </div>
            <p class="headerText">

            </p>
        </div>
    </header>
{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <div class="direction">
                <div class="row">
                    <div class="col-md-9">
                        <div class="my-object-card-cont curort-card-cont">
                            {% for hotel in hotel_list %}
                                <div class="my-object-card flex mt-30">
                                    <div class="card-image">
                                        <div class="owl-admin" class="owl-carousel">
                                            {% for image in hotel.hotelphoto_set.all|slice:'5' %}
                                                <a href="{% url 'region:hotel_detail' slug=hotel.city.slug pk=hotel.id %}"
                                                   title="{{ item }}">
                                                    <div class="item">
                                                        <div class="item-img">
                                                            {% thumbnail image.image "262x180" crop='center' as im %}
                                                                <img class="lazyOwl"
                                                                     data-src="{{ im.url }}" width="{{ im.width }}"
                                                                     height="{{ im.height }}"
                                                                     alt="{{ hotel }}">
                                                            {% endthumbnail %}
                                                        </div>
                                                    </div>
                                                </a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="card-body curort-card flex  juatifyBetween">
                                        <div class="card-body-left flex directionColumn juatifyBetween">
                                            <div class="card-body-cont">
                                                <a href="{% url 'region:hotel_detail' slug=hotel.city.slug pk=hotel.id %}"
                                                   title="{{ item }}"><p>{{ hotel }}</p></a>
                                                <p class="card-location">{{ hotel.city }}, {{ hotel.address }}</p>
                                                <p class="card-distance">Море - {{ hotel.remoteness }} м •
                                                    {% if hotel.centr %}Центр -
                                                        {{ hotel.centr }}
                                                        км</p>
                                                    {% endif %}
                                            </div>

                                            <div data-id="{{ hotel.id }}"
                                                 data-action="bookmark" data-url="{{ request.path }}"
                                                 title="Избранное">
                                                <a href="#">
                                                    {% if hotel.id|stringformat:"i" in favorite_list_ids %}
                                                        <i class="far fa-heart" style="color: #ff0000;"></i>
                                                    {% else %}
                                                        <i class="far fa-heart" style="color: #202dd9;"></i>
                                                    {% endif %}
                                                </a>
                                            </div>
                                            <div class="black-sea-icon flex">
                                                {% for option in hotel.options.all|slice:":3" %}
                                                    <span>{{ option }}</span>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="card-body-right-button flex directionColumn juatifyBetween">
                                            <div class="curort-price">
                                                <div class="curort-price-cont">
                                                    <div class="curort-price1 cur1">
                                                        {% if hotel.get_min_price %}от
                                                            {{ hotel.get_min_price }}
                                                            руб.{% else %}Не задано{% endif %}
                                                    </div>
                                                    <div class="curort-price2">за 1 сутки</div>
                                                </div>
                                                <div class="curort-price3">
                                                    <img src="{% static 'img/curort-icon1.png' %}" alt="">
                                                    <span>отзывов {{ hotel.review_set.all.count }} </span>
                                                </div>

                                            </div>
                                            <a href="{% url 'region:hotel_detail' slug=hotel.city.slug pk=hotel.id %}">
                                                <button class="show-price">Показать цены</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            {% include 'include/paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/hotel/hotel_filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object }}</title>
</head>
<body>
{{ filter.qs}}
</body>
</html>