VolnaYuga/urls.py
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from accounts.views import login_request, logout_request, password_reset_request
from core.sitemaps import HotelSitemap, RegionSitemap
from core.views import AboutPage, ContactPage, RentPage, HomePage
from django.conf import settings
from django.conf.urls.static import static

from hotel.models import Hotel
from region.views import RegionAutocomplete, HotelSearchBlock
from django.conf.urls import handler404

sitemaps = {
    'hotel': HotelSitemap,
    'region': RegionSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'city-autocomplete/',
        RegionAutocomplete.as_view(),
        name='city-autocomplete',
    ),
    path('search/', HotelSearchBlock.as_view(), name='hotel_search_block'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    path('about/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('rent/', RentPage.as_view(), name='rent'),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('page/', include('page.urls', namespace='page')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('user_queries/', include('userQueries.urls', namespace='userQueries')),
    # path('register/', register_request, name="register"),
    path('login/', login_request, name="login_s"),
    path('logout/', logout_request, name="logout_s"),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('<region_slug>/attraction/', include('attraction.urls', namespace='attraction')),
    path('review/', include('review.urls', namespace='review')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('<slug>/', include('region.urls', namespace='region')),
    path('', HomePage.as_view(), name='home'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attraction/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'attraction'

urlpatterns = [
    path('<category_slug>/', AttractionList.as_view(), name='attraction_list' ),
    path('<category_slug>/<slug>/', AttractionDetail.as_view(), name='attraction_detail' ),
]

page/urls.py
from django.urls import path
from .views import PageDetail


app_name = 'page'

urlpatterns = [
    path('<slug:slug>/', PageDetail.as_view(), name='page_detail'),
]

region/urls.py
from django.urls import path
from region.views import HotelDetail, HotelFilterByType, hotel_list, HotelFilterByService, HotelFilterByTypeAndService, \
    HotelSearchBlock
from region.views import RegionDetail


app_name = 'region'

urlpatterns = [
    path('', RegionDetail.as_view(), name='region_detail'),
    path('filter/', hotel_list, name='hotel_filter_left'),
    path('search/', HotelSearchBlock.as_view(), name='hotel_search_block'),
    path('<int:pk>/', HotelDetail.as_view(), name='hotel_detail'),
    path('<slug:type_slug>/', HotelFilterByType.as_view(), name='hotel_type_filter'),
    path('service/<slug:service_slug>/', HotelFilterByService.as_view(), name='hotel_service_filter'),
    path('<slug:type_slug>/<slug:service_slug>/', HotelFilterByTypeAndService.as_view(),
         name='hotel_type_service_filter'),

]

attraction/models.py
from django.db import models
from ckeditor.fields import RichTextField
from region.models import Region
# Create your models here.

class AttractionCategory(models.Model):
    """Категория достопримечательности"""
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория достопримечательности'
        verbose_name_plural = 'Категории достопримечательностей'


class Attraction(models.Model):
    """Достопримечательности регионов"""
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')
    meta_title = models.CharField(max_length=100, blank=True, verbose_name='Мета заголовок')
    meta_description = models.TextField(blank=True, verbose_name='Мета описание')
    category = models.ForeignKey(AttractionCategory, on_delete=models.CASCADE, verbose_name='Категория')
    region = models.ForeignKey(Region, null=True, blank=True, limit_choices_to={'is_city': True}, on_delete=models.CASCADE, verbose_name='Курорт')
    content = RichTextField(verbose_name='Описание')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    thumb = models.FileField(upload_to='images/attraction_thumb', verbose_name='Изображение')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Достопримечательность'
        verbose_name_plural = 'Достопримечательности'


class AttractionGallery(models.Model):
    """Галерея на странице"""
    attraction = models.ForeignKey(Attraction, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/attraction', verbose_name='Изображение')

    class Meta:
        verbose_name = 'Фотографию'
        verbose_name_plural = 'Галерея'

attraction/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from hotel.models import Hotel
from .models import *





class AttractionList(ListView):
    """List of category attractions"""
    model = Attraction
    template_name = 'attraction/attraction_list.html'

    def get_queryset(self):
        return Attraction.objects.filter(category__slug=self.kwargs['category_slug'])
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context= super(AttractionList, self).get_context_data(**kwargs)
        context['attraction_category'] = AttractionCategory.objects.get(slug=self.kwargs['category_slug'])
        region = Region.objects.get(slug=self.kwargs['region_slug'])
        context['region'] = region
        context['hotel_premium_list'] = Hotel.objects.filter(city=region, premium=True)
        return context

class AttractionDetail(DetailView):
    """Attraction detail"""
    model = Attraction
    template_name = 'attraction/attraction_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AttractionDetail, self).get_context_data(**kwargs)
        context['hotel_premium_list'] = Hotel.objects.filter(premium=True, city=self.object.region)
        return context

templates/attraction/attraction_detail.html
{% extends 'base.html' %}
{% load static thumbnail %}

{% block header %}
    <header id="attraction">
        <div class="container">
            {% include 'include/main-menu.html' %}
            <ul class="breadcrumb">
                <li><a href="/">Главная</a></li>
                {% if object.region.parent.parent %}
                <li><a href="{% url 'region:region_detail' slug=object.region.parent.parent.slug  %}">{{ object.region.parent.parent }}</a></li>
                {% endif %}
                <li><a href="{% url 'region:region_detail' slug=object.region.slug %}">{{ object.region }}</a></li>
                <li>{{ object }}</li>
            </ul>
            <div class="headerTitle">
                <h1>{{ object.title }}</h1>
            </div>

        </div>
    </header>
{% endblock %}
{% block content %}
    <!--SECTION INTERESTING PLACES-->
    <section class="mt-100 interesting">
        <div class="container ">
            <div class="row">
                <div class="col-md-3">


                    {% for hotel in hotel_premium_list %}
                        <div class="hotel-left mb-50">
                            <div class="card-image">
                                <img src="{% static 'img/adler-left-image.png' %}" alt="">
                            </div>
                            <div class="curort-card mt-10">
                                <div class="card-body-cont">
                                    <p><a href="{% url 'region:hotel_detail' pk=hotel.pk slug=object.region.slug %}">{{ hotel }}</a></p>
                                    <p class="card-location">{{ hotel.city }}, {{ hotel.address }}</p>
                                    <p class="card-distance">Море - {{ hotel.remoteness }} м</p>
                                </div>
                                <div class="curort-price-cont">
                                    <div class="curort-price1 cur1">
                                        от {{ hotel.get_min_price.min_price }} руб. / за 1 ночь
                                    </div>

                                </div>

                                <div class="black-sea-icon flex">
                                    <div class="black-sea-check">
                                        <img src="{% static 'img/check.png' %}" alt="check">
                                    </div>
                                    <div class="black-sea-link">
                                        <img src="{% static 'img/like.png' %}" alt="like">
                                    </div>
                                    <div class="black-sea-taxi">
                                        <img src="{% static 'img/taxi.png' %}" alt="taxi">
                                    </div>
                                    {% for option in hotel.options.all|slice:":2" %}
                                        <span>{{ option }}</span>
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                    {% endfor %}


                </div>
                <div class="col-md-9">
                    <div class="adler-right">


                        <div class="owl-admin owl-admin1" class="owl-carousel">
                            {% for item in object.attractiongallery_set.all %}
                                <div class="item">
                                    <div class="item-img">
                                        {% thumbnail item.image '825x486' crop='center' as im %}
                                            <img class="lazyOwl" src="{{ im.url }}" data-src="{{ im.url }}" {% if im.width %}width="{{ im.width }}"{% endif %} 
                                            {% if im.height %}height="{{ im.height }}"{% endif %}
                                                 alt="{{ item.image.name }}">
                                        {% endthumbnail %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="mt-80">{{ object.content|safe }}</div>

                        <!--       <div class="curort-diagram mt-100">
                                   <h2>График <span>цен, температуры воздуха и воды по месяцам в Адлере</span></h2>
                                   <ul class="flex direction-ul curort-ul">
                       <li data-show="curort1" class="">
                         <span>Цены за номер в сутки</span>
                       </li>
                       <li data-show="curort2" class="">
                         <span>Средняя температура воздуха</span>
                       </li>
                       <li data-show="curort3" class="active">
                         <span>Средняя температура воды</span>
                       </li>
                     </ul>
                                   <div class="diagram-cont relative">
                                       <div class="first-diagram flex">
                                           <div>2 820 руб.</div>
                                           <div class="diagram-dashed"></div>
                                       </div>
                                       <div class="first-diagram first-diagram1 flex">
                                           <div>2 820 руб.</div>
                                           <div class="diagram-dashed"></div>
                                       </div>
                                       <div class="diagram-body">
                                           <div class=" flex juatifyEnd">
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill feb"></div>
                                                   </div>
                                                   <span>Фев</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill mart"></div>
                                                   </div>
                                                   <span>Мар</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill april"></div>
                                                   </div>
                                                   <span>Апр</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill may"></div>
                                                   </div>
                                                   <span>Май</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill jun"></div>
                                                   </div>
                                                   <span>Июн</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill jul"></div>
                                                   </div>
                                                   <span>Июл</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill avg"></div>
                                                   </div>
                                                   <span>Агв</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill sep"></div>
                                                   </div>
                                                   <span>Сен</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill okt"></div>
                                                   </div>
                                                   <span>Окт</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill nov"></div>
                                                   </div>
                                                   <span>Ноя</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill dec"></div>
                                                   </div>
                                                   <span>Дек</span>
                                               </div>
                                               <div class="diagram-month">
                                                   <div class="diagram-month-body">
                                                       <div class="diagram-month-body-fill jan"></div>
                                                   </div>
                                                   <span>Янв</span>
                                               </div>
                                           </div>
                                           <div class="flex juatifyBetween">
                                               <div class="year1">2022</div>
                                               <div class="year2">2023</div>
                                           </div>

                                       </div>
                                   </div>
                               </div> -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--SECTION INTERESTING PLACES-->
{% endblock %}

templates/attraction/attraction_list.html
{% extends 'base.html' %}
{% load static thumbnail %}

{% block header %}
    <header id="attraction">
        <div class="container">
            {% include 'include/main-menu.html' %}
            <ul class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li><a href="{% url 'region:region_detail' slug=region.parent.slug %}">{{ region.parent }}</a></li>
                <li><a href="{% url 'region:region_detail' slug=region.slug %}">{{ region.title }}</a></li>
                <li>{{ attraction_category }}</li>
            </ul>
            <div class="headerTitle">
                <h1>{{ attraction_category }} в {{ region.title }}</h1>
            </div>

        </div>
    </header>
{% endblock %}
{% block content %}
    <!--SECTION INTERESTING PLACES-->
    <section class="mt-100 interesting">
        <div class="container ">
            <div class="good-views">
                <div class="row">
                        {% for item in attraction_list %}
                            <div class="col-md-4 col-sm-6">
                                <div class="good-views-cont">
                                    <a href="{% url 'attraction:attraction_detail' region_slug=region.slug category_slug=attraction_category.slug slug=item.slug %}">
                                        <img src="{{ item.thumb.url }}" alt="{{ item }}"></a>
                                    <h4>
                                        <a href="{% url 'attraction:attraction_detail' region_slug=region.slug category_slug=attraction_category.slug slug=item.slug %}">{{ item }}</a>
                                    </h4>
                                    <p>{{ item.meta_description|slice:"100" }}</p>
                                </div>
                            </div>
                        {% endfor %}

                </div>
            </div>
        </div>
    </section>
    <!--SECTION INTERESTING PLACES-->
{% endblock %}