VolnaYuga/urls.py
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from accounts.views import login_request, logout_request, password_reset_request
from core.sitemaps import HotelSitemap, RegionSitemap
from core.views import AboutPage, ContactPage, RentPage, HomePage
from django.conf import settings
from django.conf.urls.static import static

from hotel.models import Hotel
from region.views import RegionAutocomplete, HotelSearchBlock
from django.conf.urls import handler404

sitemaps = {
    'hotel': HotelSitemap,
    'region': RegionSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'city-autocomplete/',
        RegionAutocomplete.as_view(),
        name='city-autocomplete',
    ),
    path('search/', HotelSearchBlock.as_view(), name='hotel_search_block'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    path('about/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('rent/', RentPage.as_view(), name='rent'),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('page/', include('page.urls', namespace='page')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('user_queries/', include('userQueries.urls', namespace='userQueries')),
    # path('register/', register_request, name="register"),
    path('login/', login_request, name="login_s"),
    path('logout/', logout_request, name="logout_s"),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('<region_slug>/attraction/', include('attraction.urls', namespace='attraction')),
    path('review/', include('review.urls', namespace='review')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('<slug>/', include('region.urls', namespace='region')),
    path('', HomePage.as_view(), name='home'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    # path('register/', register_request, name="register"),
    path('login/', login_request, name="login"),
    path('logout/', logout_request, name= "logout"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('lk/', HotelList.as_view(), name='user_hotel_list'),
    path('lk/create_hotel/', HotelCreate.as_view(), name='hotel_create'),
    path('lk/<int:pk>/delete/', HotelDelete.as_view(), name='hotel_delete'),
    path('lk/<int:pk>/update/', HotelUpdate.as_view(), name='hotel_update'),
    path('lk/<int:pk>/info/', HotelDetail.as_view(), name='user_hotel_detail'),
    path('lk/<int:pk>/priceperiod/', HotelPricePeriodUpdate.as_view(), name='user_hotel_price_period_update'),
    path('lk/<int:pk>/priceperiod_delete/', price_period_delete, name='user_hotel_price_period_delete'),
    path('lk/priceupdate/', price_update, name='price_update'),
    path('lk/<int:pk>/<int:photo_pk>/delete/', HotelPhotoDelete.as_view(), name='hotel_photo_delete'),
    path('lk/<int:pk>/rules/', HotelRules.as_view(), name='hotel_rules'),
    path('lk/<int:hotel_pk>/number_create/', NumberCreate.as_view(), name='number_create'),
    path('lk/<int:pk>/image_upload/', number_image_upload, name='number_image_upload'),
    path('lk/<int:pk>/hotel_image_upload/', hotel_image_upload, name='hotel_image_upload'),
    path('lk/<int:pk>/hotel_image_delete/', hotel_image_delete, name='hotel_image_delete'),
    path('lk/<int:hotel_pk>/<int:pk>/number_update/', NumberUpdate.as_view(), name='number_update'),
    path('lk/<int:hotel_pk>/<int:pk>/number_delete/', NumberDelete.as_view(), name='number_delete'),
    path('lk/<int:image_pk>/number_image_delete/', number_image_delete, name='number_image_delete'),
    path('lk/<int:hotel_pk>/contact_create/', ContactCreate.as_view(), name='contact_create'),
    path('lk/<int:hotel_pk>/<int:pk>/', ContactUpdate.as_view(), name='contact_update'),
    path('lk/<int:hotel_pk>/<int:pk>/delete', ContactDelete.as_view(), name='contact_delete'),
    path('lk/<int:hotel_pk>/options_update/', HotelOptionUpdate.as_view(), name='hotel_options_update'),
    path('lk/<int:hotel_pk>/distance_add/', DistanceAdd.as_view(), name='hotel_distance_add'),
    path('lk/<int:hotel_pk>/<pk>/distance_delete/', DistanceDelete.as_view(), name='hotel_distance_delete'),
    path('lk/reviewlist/', HotelReviewList.as_view(), name='hotel_review_list'),
    path('lk/help/', HotelHelp.as_view(), name='hotel_help'),



]

page/urls.py
from django.urls import path
from .views import PageDetail


app_name = 'page'

urlpatterns = [
    path('<slug:slug>/', PageDetail.as_view(), name='page_detail'),
]

hotel/models.py
import datetime
from datetime import date
from django.db import models
from django.db.models import Avg, Sum, Min
from accounts.models import MyUser
from ckeditor.fields import RichTextField
from region.models import Region


class TypeofObject(models.Model):
    """Типы объектов сдачи"""
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')
    image = models.ImageField(upload_to='hotel/hoteltype', null=True, blank=True, verbose_name='Изображение')
    services = models.ManyToManyField('ServiceFilterofObject', blank=True,
                                      verbose_name='Какие критерии жилья отображать на странице')

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = ' Типы объектов размещения'

    def __str__(self):
        return self.title


class ServiceFilterofObject(models.Model):
    """Фильтр критериев удобств объектов сдачи"""
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')
    image = models.ImageField(upload_to='hotel/filterservice', null=True, blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'Критерий удобства'
        verbose_name_plural = ' Критерии удобства'

    def __str__(self):
        return self.title


OPTIONCATEGORYCHOICE = (
    ('food', ('Питание')),
    ('service', ('Удобства и услуги')),
    ('booking', ('Условия бронирования')),
)


class HotelOption(models.Model):
    """Опции объекта"""
    title = models.CharField(max_length=100, verbose_name='Название')
    comment = models.CharField(max_length=100, blank=True, verbose_name='Комментарии')
    category = models.CharField(max_length=50, choices=OPTIONCATEGORYCHOICE, default='food', verbose_name='Категория')
    icon = models.CharField(max_length=50, blank=True, verbose_name='Класс иконки font-awesome')

    class Meta:
        verbose_name = 'Опцию'
        verbose_name_plural = ' Опции для гостиниц'

    def __str__(self):
        return self.title


class Distance(models.Model):
    """Расстояния от гостиницы"""
    title = models.CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Расстояние до обьекта'
        verbose_name_plural = 'Расстояния до объектов'

    def __str__(self):
        return self.title


WALKMETHODCHOICE = (
    ('walk', ('Пешком')),
    ('avto', ('На авто')),
)


class DistanceTime(models.Model):
    """Расстояние до объектов"""
    distance = models.ForeignKey(Distance, on_delete=models.CASCADE, verbose_name='Объект расстояния')
    time = models.IntegerField(verbose_name='Время в минутах', blank=True, null=True)
    method = models.CharField(max_length=10, choices=WALKMETHODCHOICE, blank=True, null=True, verbose_name='Метод')
    hotel = models.ForeignKey('Hotel', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Гостиница')

    class Meta:
        verbose_name = 'Время до объекта'
        verbose_name_plural = 'Время до объектов'

    def __str__(self):
        return self.distance.title


BEACHCHOICE = (
    ('galka', ('Галька')),
    ('pesok', ('Песок')),
)

BEACHREMOTENESS = [
    ('100', '100'),
    ('200', '200'),
    ('500', '500'),
    ('800', '800'),
    ('1000', '1000'),
    ('1500', '1500'),
]


class HotelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True)


class Hotel(models.Model):
    """Отель"""
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='Владелец')
    pub_date = models.DateField(default=datetime.date.today, verbose_name='Дата публикации')
    title = models.CharField(max_length=100, verbose_name='Название')
    meta_title = models.CharField(max_length=100, blank=True, verbose_name='Мета заголовок')
    meta_description = models.TextField(blank=True, verbose_name='Мета описание')
    premium = models.BooleanField(default=False, verbose_name='Премиум гостиница')
    object_type = models.ManyToManyField(TypeofObject, blank=True, verbose_name='Тип жилья')
    object_service = models.ManyToManyField(ServiceFilterofObject, blank=True, verbose_name='Фильтр по критериям жилья')
    address = models.CharField(max_length=100, verbose_name='Адрес (без указания города)')
    city = models.ForeignKey(Region, on_delete=models.CASCADE, limit_choices_to={'is_city': True},
                             related_name='hotels', verbose_name='Город')
    remoteness = models.CharField(max_length=10, blank=True, choices=BEACHREMOTENESS, default=1,
                                  verbose_name='Расстояние до моря')
    beach = models.CharField(max_length=50, blank=True, choices=BEACHCHOICE, default='1000', verbose_name='Пляж')
    centr = models.CharField(max_length=20, blank=True, verbose_name='Расстояние до центра')
    options = models.ManyToManyField(HotelOption, blank=True, verbose_name='Опции')
    description = RichTextField(blank=True, verbose_name='Описание')
    video = models.URLField(blank=True, verbose_name='Ссылка на видео объекта')
    distance = models.ManyToManyField(Distance, through='DistanceTime', verbose_name='Объекты рядом')
    prepayment = models.CharField(max_length=10, blank=True,
                                  verbose_name='Размер предоплаты в % или в сутках проживания')
    free_cancel = models.CharField(max_length=100, blank=True, verbose_name='Условия бесплатной отмены брони')
    early_booking_discount = models.IntegerField(null=True, blank=True, verbose_name='Скидка на раннее бронирование')
    requisites = models.TextField(blank=True, verbose_name='Реквизиты')
    prepayments_term = models.BooleanField(default=0, verbose_name='Без предоплаты')
    minimum = models.IntegerField(blank=True, null=True, verbose_name='Минимальный срок проживания в сутках')
    chek_in = models.TimeField(blank=True, null=True, verbose_name='Время заселения')
    chek_out = models.TimeField(blank=True, null=True, verbose_name='Время выезда')
    pets = models.BooleanField(default=0, verbose_name='Размещение животных')
    child = models.BooleanField(default=0, verbose_name='Размещение детей')
    another_rules = models.TextField(blank=True, verbose_name='Другие правила')
    published = models.BooleanField(default=0, verbose_name='Опубликовать гостиницу')
    objects = models.Manager()
    filter_objects = HotelManager()

    class Meta:
        verbose_name = ' Обьект размещения'
        verbose_name_plural = ' Гостиницы'

    def __str__(self):
        return self.title

    def get_min_price(self):
        return self.numbers.all().aggregate(min_price=Min('prices__price'))['min_price']



class BookmarkHotel(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name="Пользователь")
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, verbose_name='Объект')

    def __str__(self):
        return self.user.email


class HotelPhoto(models.Model):
    """Фотографии на странице фильтрации"""
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='hotel/hotel_photo_thumb', null=True, default='profile_image/none/no-img.png',
                              verbose_name='Изображение')

    class Meta:
        verbose_name = 'Фотографию'
        verbose_name_plural = 'Фотографии объекта для страниц фильтрации'
        ordering = ['id']

    def __str__(self):
        return self.image.name


class HotelContact(models.Model):
    """Контакты объекта"""
    hotel = models.ForeignKey(Hotel, default=1, on_delete=models.CASCADE, verbose_name='Гостиница')
    phone = models.CharField(max_length=12, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Email')
    photo = models.FileField(upload_to='hotel/contacts', null=True, blank=True, verbose_name='Фотография')
    name = models.CharField(max_length=100, verbose_name='ФИО')
    skype = models.BooleanField(default=0)
    whatsapp = models.BooleanField(default=0)
    telegram = models.BooleanField(default=0)
    viber = models.BooleanField(default=0)

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты объектов размещения'

    def __str__(self):
        return self.name


class NumberOption(models.Model):
    """Опции объекта"""
    title = models.CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Опцию'
        verbose_name_plural = ' Опции для номеров'

    def __str__(self):
        return self.title


class Number(models.Model):
    ORDERCHOICE = (
        ('number', ('за номер')),
        ('people', ('за человека')),
    )

    order_choice = models.CharField(max_length=10, choices=ORDERCHOICE, default='за номер',
                                    verbose_name='Цена в объявлении')
    hotel = models.ForeignKey(Hotel, default=1, on_delete=models.CASCADE, related_name='numbers', verbose_name='Отель')
    title = models.CharField(max_length=100, verbose_name='Название')
    room_number = models.IntegerField(null=True, blank=True, verbose_name='Количество комнат')
    sleep_place = models.IntegerField(null=True, blank=True, verbose_name='Количество спальных мест')
    room_square = models.IntegerField(null=True, blank=True, verbose_name='Площадь комнаты')
    additional_palces = models.IntegerField(null=True, blank=True, verbose_name='Дополнительные места')
    furniture = RichTextField(blank=True, verbose_name='Мебель')
    options = models.ManyToManyField(NumberOption, blank=True, verbose_name='Опции')

    class Meta:
        verbose_name = ' Номер'
        verbose_name_plural = ' Номера'

    def __str__(self):
        return self.hotel.title + ' - ' + self.title

    def get_min_price(self):
        """Самая низкая цена номера"""
        return Price.objects.filter(number=self).aggregate(min_price=Min('price'))['min_price']

    def get_price_today(self):
        """Цена номера на сегодня"""

templates/accounts/lk_contact_create.html
{% extends 'lk_base.html' %}
{% load crispy_forms_tags static %}
{% block content %}
    <div class="col-md-9">
        <div class="myObject-right">
            <h1>Добавление контакта</h1>
            <div class="add-object-card-cont mb-100">
                <form method="post" enctype="multipart/form-data" class="add-object-form">
                    {% csrf_token %}
                    <input type="text" name="phone" value="{{ form.instance.phone }}"
                           placeholder="Введите телефон" required
                           style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAfBJREFUWAntVk1OwkAUZkoDKza4Utm61iP0AqyIDXahN2BjwiHYGU+gizap4QDuegWN7lyCbMSlCQjU7yO0TOlAi6GwgJc0fT/fzPfmzet0crmD7HsFBAvQbrcrw+Gw5fu+AfOYvgylJ4TwCoVCs1ardYTruqfj8fgV5OUMSVVT93VdP9dAzpVvm5wJHZFbg2LQ2pEYOlZ/oiDvwNcsFoseY4PBwMCrhaeCJyKWZU37KOJcYdi27QdhcuuBIb073BvTNL8ln4NeeR6NRi/wxZKQcGurQs5oNhqLshzVTMBewW/LMU3TTNlO0ieTiStjYhUIyi6DAp0xbEdgTt+LE0aCKQw24U4llsCs4ZRJrYopB6RwqnpA1YQ5NGFZ1YQ41Z5S8IQQdP5laEBRJcD4Vj5DEsW2gE6s6g3d/YP/g+BDnT7GNi2qCjTwGd6riBzHaaCEd3Js01vwCPIbmWBRx1nwAN/1ov+/drgFWIlfKpVukyYihtgkXNp4mABK+1GtVr+SBhJDbBIubVw+Cd/TDgKO2DPiN3YUo6y/nDCNEIsqTKH1en2tcwA9FKEItyDi3aIh8Gl1sRrVnSDzNFDJT1bAy5xpOYGn5fP5JuL95ZjMIn1ya7j5dPGfv0A5eAnpZUY3n5jXcoec5J67D9q+VuAPM47D3XaSeL4AAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
                    <input type="email" name="email" value="{{ form.instance.email }}" placeholder="Введите E-mail" required>
                    <input type="text" name="name" value="{{ form.instance.name }}"
                           placeholder="Введите имя или должность" required>
                    <div class="form-chackbox-cont flex ">
                        <p>Сервисы, доступные по этому номеру:</p>
                        <div class="form-chackbox">
                            <ul class="left-filter1-ul listNone addContactUl">
                             {% for field in form %}
                        {% if field.field.widget.input_type == 'checkbox' %}
                            <li>
                                    <div class="checkbox flex alignCenter juatifyBetween">
                                        {{ field }}
                                        <label for="{{ field.id_for_label }}"><img src="/static/img/{{ field.label }}.svg"
                                                                      alt=""><span>{{ field.label }}</span></label>
                                    </div>
                                </li>
                                 {% endif %}
                    {% endfor %}


                            </ul>
                        </div>
                    </div>
                    <button class="submit">добавить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/lk_home.html
{% extends 'lk_base.html' %}
{% load static thumbnail %}
{% block meta %}
    <meta name="description" content="Страница личного кабинета {{ request.user }}">
    <title>Личный кабинет</title>
{% endblock %}
{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li><a href="{% url 'accounts:user_hotel_list' %}">Главная</a></li>
    </ul>
{% endblock %}
{% block content %}
    <div class="col-md-9">
        <div class="myObject-right">
            <h1>Мои объекты</h1>
            <a href="{% url 'accounts:hotel_create' %}">
                <button class="newObject">
                <span class="plusCont">
                  <i class="fa fa-plus" aria-hidden="true"></i>
                </span>
                    добавить объект
                </button>
            </a>
            <div class="my-object-card-cont mb-100">
                {% for hotel in object_list %}
                    <div class="my-object-card flex mt-30">
                        <div class="card-image">
                            <div class="owl-admin" class="owl-carousel">
                                {% if hotel.hotelphoto_set.all %}
                                    <div class="item">
                                        <div class="item-img">
                                            {% thumbnail hotel.hotelphoto_set.first.image "262x180" crop="center" as im %}
                                                <img src="{{ im.url }}" {% if im.width %}width="{{ im.width }}"{% endif %} 
                                                         {% if im.height %}height="{{ im.height }}"{% endif %}
                                                     alt="Lazy Owl Image">
                                            {% endthumbnail %}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="item">
                                        <div class="item-img">
                                            <img width="262" height="180" class="lazyOwl"
                                                 data-src="{% static 'img/empty.png' %}" alt="Lazy Owl Image">
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-body flex  juatifyBetween">
                            <div class="card-body-left flex directionColumn juatifyBetween">
                                <div class="card-body-cont">
                                    <p>{{ hotel.title }}</p>
                                    <p class="card-location">{{ hotel.city }}, {{ hotel.address }}</p>
                                </div>
                                <div class="view flex alignCenter"><i class="icon-Union"></i><span>0 просмотров</span>
                                </div>
                            </div>
                            <div class="card-body-right flex directionColumn juatifyBetween">
                                <a href="{% url 'accounts:user_hotel_detail' pk=hotel.id %}">
                                    <button>редактировать</button>
                                </a>
                                <a href="{% url 'accounts:hotel_delete' pk=hotel.id %}">
                                    <button class="delete-card">удалить</button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>

        </div>
    </div>
{% endblock %}


<h2>Список объектов</h2>
{% for hotel in object_list %}
    <ul>
        <li><a href="{% url 'accounts:user_hotel_detail' pk=hotel.id %}">{{ hotel }}</a> - <a
                href="{% url 'accounts:hotel_update' pk=hotel.id %}">Редактировать</a> - <a
                href="{% url 'accounts:hotel_delete' pk=hotel.id %}">Удалить</a>
    </ul>
{% endfor %}

templates/accounts/lk_hotel_confirm_delete.html
{% extends 'lk_base.html' %}

{% block content %}
    <div class="col-md-9">
        <div class="myObject-right">
            <h1>{{ object }}</h1>
            <div class="add-object-card-cont mb-100">
                <form method='POST'>
                    {% csrf_token %}
                    <h4>Вы хотите удалить "{{ object }}"?</h4>
                    <button class="submit">Удалить</button>
                    <a href="javascript:history.back()">Отмена</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/lk_hotel_create.html
{% extends 'lk_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-9">
          <div class="myObject-right">
            <h1>Добавление объекта</h1>
            <div class="add-object-card-cont mb-100">
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                     <button class="submit">добавить</button>
                </form>
            </div>
          </div>
        </div>
{% endblock %}

templates/accounts/lk_hotel_help.html
{% extends 'lk_base.html' %}
{% load static %}
{% block content %}
    <div class="col-md-9">
        <div class="myObject-right mb-100 help">
            <h1>FAQ</h1>
            {% if object.content_1 %}
            <div class="mb-50">
                <div class="row">
                    <div class="col-md-12">
                        {{ object.content_1|safe }}
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="row">
                {% if faq_objects %}
                {% for faq_onject in faq_objects %}
                <div class="col-md-12 mb-10">
                    <div class="faq faq-block">
                        <div class="faq-block-title flex juatifyBetween">
                            <h4>{{ faq_onject.question }}</h4>
                            <div class="collaps-button2">
                                <i class="fa fa-angle-down"></i>
                            </div>
                        </div>
                        <p>{{ faq_onject.answer }}</p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% if object.content_2 %}
            <div class="row mt-50">
                <div class="col-md-12">
                    {{ object.content_2|safe }}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/accounts/lk_hotel_priceperiod.html
{% extends 'lk_base.html' %}
{% load crispy_forms_tags %}
{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li><a href="/accounts/lk/{{ object.id }}/info/#tab-priceTab">Вернуться в цены</a></li>
    </ul>
{% endblock %}
{% block content %}
    <div class="col-md-9">
        <div class="myObject-right">
            <h1>Редактирование периодов цен для гостиницы</h1>
            <div class="mb-100">
                <div class="col-md-12">
                    <div class="row">
                        <script>
                            $(function (event) {
                                $('.datepicker').val(event.currentTarget.val());
                            });
                        </script>
                        <script type="text/javascript">

                        </script>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}'/>
                            {{ formset.management_form }}
                            <div class="hidden-periuds">

                                {% for form in formset %}
                                    <div class="card-body-right hidden-periud flex alignCenter
                                            {% if form.start.value %}{% else %}d-none{% endif %}">
                                        {{ form }}
                                        {% if form.start.value %}
                                            <button data-id="{% url 'accounts:user_hotel_price_period_delete' pk=form.instance.id %}"
                                                    class="delete-card">удалить
                                            </button>{% else %}{% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                            <a href="" class="addPeriud">
                                <button class="newObject">
                     <span class="plusCont">
                       <i class="fa fa-plus" aria-hidden="true"></i>
                     </span>
                                    добавить период
                                </button>
                            </a>
                            <input class="newObject mt-20" type="submit" value="Сохранить">
                        </form>
                    </div>
                </div>
                <h5 class="mt-20"><a href="/accounts/lk/{{ object.id }}/info/#tab-priceTab">Вернуться к ценам</a></h5>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/lk_hotel_update.html
{% extends 'lk_base.html' %}
{% load static crispy_forms_tags thumbnail %}
{% block content %}
    <div class="col-md-9">
        <div class="myObject-right">
            <h1>{{ object }}</h1>
            <div class="add-object-card-cont mb-100">
                <!--<form enctype='multipart/form-data' action="{% url 'accounts:hotel_image_upload' pk=object.id %}"
                      method="POST" class="dropzone dz" id="my-dropzone">
                    {% csrf_token %}

                    <div class="row">
                        {% for image in object.hotelphoto_set.all %}
                            <div class="mr-10 mb-10">   {% thumbnail image.image "170x100" crop="center" as im %}
                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                            {% endthumbnail %}
                            </div>
                        {% endfor %}
                    </div>
                 <div class="dz-message" data-dz-message><span>Перетащите сюда фото или просто нажмите на область</span></div>
                    <div class="fallback">
                        <input name="file" type="file" multiple/>
                    </div>
                </form> -->
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form|crispy }}
                    <button class="submit">добавить</button>
                </form>
            </div>
        </div>
    </div>
    {{ form.media }}
{% endblock %}