VolnaYuga/urls.py
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from accounts.views import login_request, logout_request, password_reset_request
from core.sitemaps import HotelSitemap, RegionSitemap
from core.views import AboutPage, ContactPage, RentPage, HomePage
from django.conf import settings
from django.conf.urls.static import static

from hotel.models import Hotel
from region.views import RegionAutocomplete, HotelSearchBlock
from django.conf.urls import handler404

sitemaps = {
    'hotel': HotelSitemap,
    'region': RegionSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'city-autocomplete/',
        RegionAutocomplete.as_view(),
        name='city-autocomplete',
    ),
    path('search/', HotelSearchBlock.as_view(), name='hotel_search_block'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),
    path('about/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('rent/', RentPage.as_view(), name='rent'),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('page/', include('page.urls', namespace='page')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('user_queries/', include('userQueries.urls', namespace='userQueries')),
    # path('register/', register_request, name="register"),
    path('login/', login_request, name="login_s"),
    path('logout/', logout_request, name="logout_s"),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('<region_slug>/attraction/', include('attraction.urls', namespace='attraction')),
    path('review/', include('review.urls', namespace='review')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('<slug>/', include('region.urls', namespace='region')),
    path('', HomePage.as_view(), name='home'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    # path('register/', register_request, name="register"),
    path('login/', login_request, name="login"),
    path('logout/', logout_request, name= "logout"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('lk/', HotelList.as_view(), name='user_hotel_list'),
    path('lk/create_hotel/', HotelCreate.as_view(), name='hotel_create'),
    path('lk/<int:pk>/delete/', HotelDelete.as_view(), name='hotel_delete'),
    path('lk/<int:pk>/update/', HotelUpdate.as_view(), name='hotel_update'),
    path('lk/<int:pk>/info/', HotelDetail.as_view(), name='user_hotel_detail'),
    path('lk/<int:pk>/priceperiod/', HotelPricePeriodUpdate.as_view(), name='user_hotel_price_period_update'),
    path('lk/<int:pk>/priceperiod_delete/', price_period_delete, name='user_hotel_price_period_delete'),
    path('lk/priceupdate/', price_update, name='price_update'),
    path('lk/<int:pk>/<int:photo_pk>/delete/', HotelPhotoDelete.as_view(), name='hotel_photo_delete'),
    path('lk/<int:pk>/rules/', HotelRules.as_view(), name='hotel_rules'),
    path('lk/<int:hotel_pk>/number_create/', NumberCreate.as_view(), name='number_create'),
    path('lk/<int:pk>/image_upload/', number_image_upload, name='number_image_upload'),
    path('lk/<int:pk>/hotel_image_upload/', hotel_image_upload, name='hotel_image_upload'),
    path('lk/<int:pk>/hotel_image_delete/', hotel_image_delete, name='hotel_image_delete'),
    path('lk/<int:hotel_pk>/<int:pk>/number_update/', NumberUpdate.as_view(), name='number_update'),
    path('lk/<int:hotel_pk>/<int:pk>/number_delete/', NumberDelete.as_view(), name='number_delete'),
    path('lk/<int:image_pk>/number_image_delete/', number_image_delete, name='number_image_delete'),
    path('lk/<int:hotel_pk>/contact_create/', ContactCreate.as_view(), name='contact_create'),
    path('lk/<int:hotel_pk>/<int:pk>/', ContactUpdate.as_view(), name='contact_update'),
    path('lk/<int:hotel_pk>/<int:pk>/delete', ContactDelete.as_view(), name='contact_delete'),
    path('lk/<int:hotel_pk>/options_update/', HotelOptionUpdate.as_view(), name='hotel_options_update'),
    path('lk/<int:hotel_pk>/distance_add/', DistanceAdd.as_view(), name='hotel_distance_add'),
    path('lk/<int:hotel_pk>/<pk>/distance_delete/', DistanceDelete.as_view(), name='hotel_distance_delete'),
    path('lk/reviewlist/', HotelReviewList.as_view(), name='hotel_review_list'),
    path('lk/help/', HotelHelp.as_view(), name='hotel_help'),



]

page/urls.py
from django.urls import path
from .views import PageDetail


app_name = 'page'

urlpatterns = [
    path('<slug:slug>/', PageDetail.as_view(), name='page_detail'),
]

core/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

class StaticData(models.Model):
    """Static data on site"""
    logo = models.ImageField(blank=True, upload_to='core/images', verbose_name='Логотип')
    logo_footer = models.ImageField(blank=True, upload_to='core/images', verbose_name='Логотип в подвале')
    banner = models.ImageField(blank=True, upload_to='core/images', verbose_name='Баннер')
    phone = models.CharField(max_length=15,blank=True, verbose_name='Телефон')
    email = models.EmailField(blank=True, verbose_name='Электронная почта')

    class Meta:
        verbose_name = 'Статические данные сайта'
        verbose_name_plural = 'Статические данные сайта'

    def __str__(self):
        return 'Логотипы и контактная информация'

templates/include/base_modal_window.html
<div class="modal-window" id="{% block modal_window_id %}{% endblock  %}">
  <div class="modal-window__wrapper">
    <div class="modal-window__content">
      <div class="modal-window__close"></div>
      {% block modal_window %} {% endblock %}
    </div>
  </div>
</div>

templates/include/form_search.html
{% load hotel_tags %}
{{ form.media }}
<form action="{% url 'hotel_search_block' %}">
    <div class="form-cont flex">
        <div class="location">
            <label>
                Место отдыха?<br>
                {{ form.city }}
            </label>
        </div>
        <div class="enter">
            <label>
                Заезд<br>
                <input type="text" placeholder="Дата" class="datepicker">
            </label>
        </div>
        <div class="exit">
            <label>
                Выезд<br>
                <input type="text" placeholder="Дата" class="datepicker">
            </label>
        </div>
        <div class="guest-count">
            <label>
                Количество гостей<br>
                <input type="text" placeholder="Кто поедет?">
            </label>
        </div>
        <button class="submit">найти</button>
    </div>
</form>

templates/include/lk_left_menu.html
<div class="col-md-3">
  <ul class="myObjectUl listNone">
      {% url 'accounts:user_hotel_list' as orders_list_url %}
    <li class="tab-item {% if request.path == orders_list_url %} active{% endif %}"><a href="{% url 'accounts:user_hotel_list' %}"><i class="icon-home"></i><span>Мои объекты</span></a></li>
    {% url 'accounts:hotel_review_list' as orders_list_url %}
      <li class="tab-item {% if request.path == orders_list_url %} active{% endif %}"><a href="{% url 'accounts:hotel_review_list' %}"><i class="icon-review"></i><span>Отзывы</span></a></li>
    {% url 'accounts:hotel_help' as orders_list_url %}
      <li class="tab-item {% if request.path == orders_list_url %} active{% endif %}"><a href="{% url 'accounts:hotel_help' %}"><i class="icon-help"></i><span>FAQ</span></a></li>
  </ul>
</div>

templates/include/lk_menu_top.html
<ul class="flex direction-ul main-ul">
  <li class="active" data-show="mainDiv">
    <span>Основное</span>
  </li>
  <li data-show="mainImage">
    <span>Фотографии</span>
  </li>
  <li data-show="roomTab" class="">
    <span>Номера</span>
  </li>
  <li data-show="priceTab">
    <span>Цены</span>
  </li>
  <li data-show="descriptionTab">
    <span>Расстояние</span>
  </li>
  <li data-show="ruleTab">
    <span>Правила</span>
  </li>
 <!-- <li data-show="stockTab">
    <span>Акции</span>
  </li> -->
</ul>

templates/include/modal_window_login.html
{% extends 'include/base_modal_window.html' %}

{% block modal_window_id %}login-window{% endblock  %}
{% block modal_window %}
<div class="loginForm">
  <h2 class="text-align-center">Авторизация</h2>
  <form method="post">
    {% csrf_token %}
    <div>
      <input type="email" name="username" id="id_username" placeholder="Ваш E-mail" required />
      <div class="msg" id="msgl_username">
      </div>
    </div>
    <div>
      <input type="password" name="password" id="id_password" placeholder="Ваш пароль" required />
    </div>
    <button>Войти</button>
    <p>
      Авторизуясь, вы соглашаетесь с правилами использования сервиса и обработки
      <a href="/page/konfiden/">персональных данных.</a>
    </p>
  </form>
  <div class="form-footer">
    <p>
      У вас еще нет аккаунта?
      <span id="open-register-modal">Зарегистрироваться</span>
    </p>
  </div>
</div>
{% endblock %}

templates/include/modal_window_register.html
{% extends 'include/base_modal_window.html' %}

{% block modal_window_id %}registration-window{% endblock  %}
{% block modal_window %}
<div class="loginForm">
    <h2 class="text-align-center">Заявка на регистрацию</h2>
    <form method="post"> {% csrf_token %}
        <div>
            <input type="text" name="username" id="id_username_reg" placeholder="Ваше имя" required>
            <div class="msg" id="msgr_username">
            </div>
        </div>
        <div>
            <input type="email" name="email" id="id_email" placeholder="Ваш E-mail" required>
            <div class="msg" id="msgr_email">
            </div>
        </div>
        <div>
            <input class="phone-maske" type="text" name="phone" id="id_phone" placeholder="Ваш телефон" required>
            <div class="msg" id="msgr_phone">
            </div>
        </div>
        <button>Отправить заявку</button>
        <p class="bold">После отправки заявки наш менеджер свяжется с Вами для выяснения деталей.</p>
        <p>Нажимая кнопку "Отправить", вы соглашаетесь с правилами использования сервиса и обработки <a href="/page/konfiden/">персональных данных.</a></p>
    </form>
    <div class="form-footer">
        <p>У вас уже есть аккаунт? <span class="open-login-modal">Войдите</span></p>
    </div>
</div>
{% endblock %}

templates/include/paginator.html
{% if hotel_list.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
        <ul class="pagination">
            {% if hotel_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">Первая</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ hotel_list.previous_page_number }}">
                        Предыдущая
                    </a>
                </li>
            {% endif %}
            {% for i in hotel_list.paginator.page_range %}
                {% if hotel_list.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if hotel_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ hotel_list.next_page_number }}">
                        Следующая
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ hotel_list.paginator.num_pages }}">
                        Последняя
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/include/script.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
<script src="{% static 'script/owl.carousel.js' %}"></script>
<script src="{% static 'script/swiper.js' %}"></script>
<script src="{% static 'script/script.js' %}"></script>
<script src="{% static 'script/dropzone.js' %}"></script>
<script>
    setTimeout(function () {
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () {
                (m[i].a = m[i].a || []).push(arguments)
            };

            m[i].l = 1 * new Date();
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })

        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(89244905, "init", {

            clickmap: true,

            trackLinks: true,

            accurateTrackBounce: true,

            webvisor: true

        });
    }, 3000);
</script>
<script src="{% static 'script/modal_window.js' %}"></script>
<script src="{% static 'script/input_mask.js' %}"></script>

<noscript>
    <div><img src="https://mc.yandex.ru/watch/89244905" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript>

<!-- /Yandex.Metrika counter -->